### ISSUE TITLE
Meteor TypeError: $activeEl.position(...) is undefined

### ISSUE THREAD

**Issue by beobast** [yuku-t/jquery-textcomplete#127] opened 2014-10-07 16:09 UTC
On Meteor, I have this error (l.581, in _setScroll function) : 
![textcomplete](https://cloud.githubusercontent.com/assets/7230289/4545560/d4569ce6-4e3b-11e4-9d6d-a8d60a4b3060.png)

If I use this old version : 
https://github.com/stubailo/murshed/blob/master/client/jquery.textcomplete.js
I don't have this issue.

**Comment by yuku-t** [comment] 2016-03-11 03:49
I'm not sure the problem is still alive, so I close this. Please drop me a line if it has not been fixed yet.

**Closed by yuku-t** 2016-03-11 03:49 UTC
Labels: bug
