### ISSUE TITLE
Two textareas with different textcompletes in one page doesn't work

### ISSUE THREAD

**Issue by make** [yuku-t/jquery-textcomplete#157] opened 2015-03-05 12:00 UTC
I have two textareas with different textcompletes in same page:
```javascript
$('#textarea1').textcomplete([{
    match: /(^)(.+)$/,
    search: search1,
    replace: replace1
}]);

$('#textarea2').textcomplete([{
    match: /(^)(.+)$/,
    search: search2,
    replace: replace2
}]);
```
Both of them show completions correctly. But when I choose an item from one's dropdown then at the same time unexpectedly also the other textarea gets value selected from it's dropdown.
This patch fixes that problem:
```
--- a/src/dropdown.js
+++ b/src/dropdown.js
@@ -56,16 +56,12 @@
     findOrCreateElement: function (option) {
       var $parent = option.appendTo;
       if (!($parent instanceof $)) { $parent = $($parent); }
-      var $el = $parent.children('.dropdown-menu')
-      if (!$el.length) {
-        $el = $('<ul class="dropdown-menu"></ul>').css({
-          display: 'none',
-          left: 0,
-          position: 'absolute',
-          zIndex: option.zIndex
-        }).appendTo($parent);
-      }
-      return $el;
+      return $('<ul class="dropdown-menu"></ul>').css({
+        display: 'none',
+        left: 0,
+        position: 'absolute',
+        zIndex: option.zIndex
+      }).appendTo($parent);
     }
   });
```

**Comment by eugene-rozov** [comment] 2015-03-24 18:25
Could be duplicate of https://github.com/yuku-t/jquery-textcomplete/issues/130

**Comment by gregeinfrank** [comment] 2015-03-31 20:33
I'm also running into this bug

**Closed** 2015-07-02 08:30 UTC
Labels: bug
