### ISSUE TITLE
Dropdown doesn't appear after an autocomplete has completed

### ISSUE THREAD

**Issue by dflynn5008** [yuku-t/jquery-textcomplete#186] opened 2015-07-20 19:19 UTC
So I have two strategies, one looking for '@' and one looking for '#' if I complete an autocomplete, like @car, and then type an '@' or a "#' afterwards, my dropdown doesn't come up, until I do something else on the keyboard (type, space, backspace)
This behavior happens in the demos here as well. 
Is there a workaround for this so that the drop down comes down after an autocomplete happens?

**Comment by yuku-t** [comment] 2016-03-11 03:55
Close the issue because I couldn't reproduce the issue with v1.1.0

**Closed by yuku-t** 2016-03-11 03:55 UTC
Labels: bug
