### ISSUE TITLE
contenteditable=true breaks on enter key, won't allow multiple lines in FF 33.1

### ISSUE THREAD

**Issue by four01** [yuku-t/jquery-textcomplete#142] opened 2014-11-23 00:57 UTC
Firstly, thanks for such a useful plugin!

This bug seems to be Firefox specific as Chrome works fine.

I've combined some code that makes use of emojione (as per their example). Everything works great on a simple HTML textarea element, but if the exact same code is changed to use a contenteditable=true div element, then pressing the enter key after selection brings up the dropdown again and moves the cursor to the start of the div, rather than inserting a new line as expected.

The attached image shows what happens after this series of events:
* Click in the editable div
* Enter the text ":chicke" (without the quotes)
* Press ENTER key to select "chicken"
* Press ENTER key again

Instead of a new line being inserted, the dropdown opens again and the cursor moves to the start of the editable div.
![chicken](https://cloud.githubusercontent.com/assets/7435359/5156228/7f28aa1a-7281-11e4-85f5-90c9a231c6b4.png)

Worth mentioning that the demo on http://yuku-t.com/jquery-textcomplete/ works fine. 

Here is the code I'm using:
```javascript
$(document).ready(function() {
    $('[contenteditable="true"]').textcomplete([
        { // emoji strategy
            match: /\B:([\-+\w]+)$/,
            search: function (term, callback) {
                var results = [];
                var results2 = [];
                var results3 = [];
                $.each(emojis, function (shortname, data) {
                    if (shortname.indexOf(term) > -1) {
                        results.push(shortname);
                    } else {
                        if ((data.aliases !== null) && (data.aliases.indexOf(term) > -1)) {
                            results2.push(shortname);
                        }
                        else if ((data.keywords !== null) && (data.keywords.indexOf(term) > -1)) {
                            results3.push(shortname);
                        }
                    }
                });

                if (term.length >= 3) {
                    results.sort(function (a, b) {
                        return (a.length > b.length);
                    });
                    results2.sort(function (a, b) {
                        return (a.length > b.length);
                    });
                    results3.sort();
                }
                var newResults = results.concat(results2).concat(results3);

                callback(newResults);
            },
            template: function (shortname) {
                return '<img class="emojione" src="//abs.twimg.com/emoji/v1/72x72/' + emojis[shortname].unicode.toLowerCase() + '.png"> :' + shortname + ':';
            },
            replace: function (shortname) {
                return ':' + shortname + ': ';
            },
            index: 1,
            maxCount: 10
        }
    ]);
});
```

**Comment by yuku-t** [comment] 2016-03-11 03:49
I'm not sure the problem is still alive, so I close this. Please drop me a line if it has not been fixed yet.

**Closed by yuku-t** 2016-03-11 03:49 UTC
